### ISSUE TITLE
When editing Schemas, changes are not saved

### ISSUE THREAD

**Issue by twoxfh** [Mermade/openapi-gui#10]
I really like this editor, however, I have found an issue, it does not save schema edits in the schema editor.

Using Chrome and Firefox:
1. Click Schemas
2. Click Edit Schema 
3. Insert or Edit an existing property
4. Click Save
5. Click Close
6. Click Export Json

After reviewing the Json export, I do not see any of my changes. Appreciate the help in solving this issue.

**Comment by MikeRalphson** [comment]
Thanks for the detailed bug report @twoxfh - I'll take a look. It's a new feature so there may be some issues.

**Comment by MikeRalphson** [comment]
@twoxfh Thanks again for reporting this, it was a cut-and-paste error, and should now be fixed. I'd appreciate it if you could re-test?

**Comment by twoxfh** [comment]
That solved it, thanks.
