### ISSUE TITLE
Only operations with descriptions are expandable

### ISSUE THREAD

**Issue by twoxfh** [Mermade/openapi-gui#11]
In Firefox and Chrome

1. Go to petstore sample
2. Add an operation or click to expand any operation that does not have a description.
3. Operation does not expand.

There is an issue with the default description logic on creation and handling if the operation doesn't have a description. Method.js line 122 needs this info.

**Comment by MikeRalphson** [comment]
I've made a fix to the display of requestBodies which I believe should fix the problem you're seeing.

It isn't directly to do with missing descriptions, or the `tagsInput` call on method.js line 122, so I'd appreciate it if you could let me know whether this fixes it for you, or if you're still seeing issues.

Many thanks again for the bug report!

**Comment by MikeRalphson** [comment]
No also fixed for callback operations.

**Comment by twoxfh** [comment]
This fixes the issue thanks! I have noticed if you import a swagger spec, it properly gets converted (I am able to see it in the UI), however, the UI has issues opening some operations. I have not nailed down what I think might be the case. I will create another issue if I do.

**Comment by MikeRalphson** [comment]
Thanks again. Yes, seeing something related to `method.externalDocs` being undefined... will take a look.

**Comment by MikeRalphson** [comment]
@twoxfh Issue with converted Swagger 2.0 definitions should hopefully be sorted now. Thanks.
