### ISSUE TITLE
The example Heroku app has an Application Error

### ISSUE THREAD

**Issue by roppa** [Mermade/openapi-gui#13]
The https://openapi-gui.herokuapp.com/ has an 'Application Error'.

**Comment by MikeRalphson** [comment]
Ah yes, related to https://github.com/Mermade/swagger2openapi/issues/20

Thanks for reporting.

We're over our quota at Heroku for this month. I'll try and put up a copy on appspot.com later.

**Comment by roppa** [comment]
Ah ok. Thanks!

**Comment by MikeRalphson** [comment]
A copy of the v3 demo is now up at http://openapi-gui.appspot.com/

Can we leave this issue open until Oct 1st in case anyone else needs it?

**Comment by roppa** [comment]
Ah yes, of course. Thanks for your work on this, looking great!

**Comment by MikeRalphson** [comment]
App is back available at the original link as the quota has reset. Thanks again for reporting.
