### ISSUE TITLE
Heroku app is offline

### ISSUE THREAD

**Issue by gmmarc** [Mermade/openapi-gui#23]
Hi,

The Heroku app has been offline at least for a couple of days:

![image](https://user-images.githubusercontent.com/7556242/35708005-5f73bd2c-07ac-11e8-93a3-b2168a8a38bf.png)

Reproducing steps:
1. Access https://openapi-gui.herokuapp.com/

Thanks!

**Comment by MikeRalphson** [comment]
As per the link at the top of the repo, openapi-gui is now hosted at https://mermade.github.io/openapi-gui/ - but I've just noticed I need to update the README further down, thanks!

**Comment by MikeRalphson** [comment]
README updated, thanks again.

**Comment by gmmarc** [comment]
Thanks to you! :smile:
