### ISSUE TITLE
Make Live-version work

### ISSUE THREAD

**Issue by MShekow** [Mermade/openapi-gui#24]
The version available at https://mermade.github.io/openapi-gui/ is horribly buggy.

You cannot edit a just-created schema.
Proof:
Open https://mermade.github.io/openapi-gui/ go to Schemas, click + to add a new one, give it a name, then click on the edit icon and see it break.

You cannot create a _Request body_ for new operations. Just try to create a new path and for that create an operation and try to add a request body.

Other elements might be buggy too, I didn't bother testing them.

Just try it out for yourself. I tested it with Firefox and Chrome.

Cheers!

**Comment by MikeRalphson** [comment]
Cheers indeed.

**Comment by MikeRalphson** [comment]
Missing functionality for adding a new `requestBody` and renaming a `schema` implemented.

**Comment by andrewheekin** [comment]
I still dont see the ability to add a new requestBody parameter, only to edit the description
