### ISSUE TITLE
OpenAPI v3 keywords 

### ISSUE THREAD

**Issue by lexxito** [Mermade/openapi-gui#27]
Good day! 

Does OpenAPI-GUI have keywords support? 
I was trying to use a keyword 'allOf', but it doesn't seem to work. 

![screenshot from 2018-06-05 11-35-55](https://user-images.githubusercontent.com/5947289/40968057-ecc9c90a-68b4-11e8-9d45-296dcfd282e0.png)
![screenshot from 2018-06-05 11-36-38](https://user-images.githubusercontent.com/5947289/40968069-f4d6779c-68b4-11e8-8432-87a349a3b67b.png)

As far as I understood allOf takes an array of object definitions that are used for independent validation but together compose a single object(https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not).

**Comment by MikeRalphson** [comment]
Could you elaborate on what exactly doesn't work?

**Comment by lexxito** [comment]
I might be mistaken but It would make much sense for me if after uploading yaml spec file which has keywords it will be displayed as the merged object. not the list of 'allof'

**Comment by MikeRalphson** [comment]
I don't think so. JSON schema `allOf` means the instance must be valid against all if these separate schemas. It does not mean merge them.

**Comment by lexxito** [comment]
according to this [https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/](page) : 'allOf' takes an array of object definitions that are used for independent validation but together compose a single object.
The thing you have described is more about 'anyof'

**Comment by MikeRalphson** [comment]
From the page you linked to:

*  oneOf – validates the value against exactly one of the subschemas
*  allOf – validates the value against **all** the subschemas
*  anyOf – validates the value against any (one or more) of the subschemas

By "compose a single object" it means that the object instance **being validated** is a single object, not that the schemas listed in the `allOf` are merged into one object.

See also https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.22

OpenAPI-GUI is designed to edit your schemas as you have written them. If you want to merge them, you should do so in your OAS document. There would be no way of untangling a merged `allOf` schema to write it back to the exported OAS document.
