### ISSUE TITLE
Enum not correctly exported

### ISSUE THREAD

**Issue by driesg** [Mermade/openapi-gui#28]
**Steps to reproduce:**

1. set up an enum as Query param:
<img src="https://s3-ap-southeast-2.amazonaws.com/monosnap-dries/OpenAPI-GUI_v3.0.0_2018-07-03_15-47-40.png" />

2. Export as YAML (or JSON)
<img src="https://s3-ap-southeast-2.amazonaws.com/monosnap-dries/OpenAPI-GUI_v3.0.0_2018-07-03_15-51-25.png" />

3. Open the YAML file in VS code with openapi-lint extension installed ;) (or swagger editor): **errors!**
<img src="https://s3-ap-southeast-2.amazonaws.com/monosnap-dries/openapi.yaml_2018-07-03_15-54-01.png" />

**Expected result:**
Both `enum` and `default` should sit under schema.

Thanks for the great tools @MikeRalphson , let me know if you need anything else from me

**Comment by MikeRalphson** [comment]
Thanks for the report! Looks like a missed change from when we moved from OpenAPI 2.0 to 3.0.x

**Comment by MikeRalphson** [comment]
Should be fixed in the current version now, please chase if not, and thanks again for reporting it and the detail above!

**Comment by driesg** [comment]
wow awesome turnaround 👏 fix confirmed, thanks!

I did have to delete the old parameter to get rid of the old values first but that's not really an issue.
