### ISSUE TITLE
dependencies needs babel-runtime

### ISSUE THREAD

**Issue by philipp** [Mermade/openapi-gui#29]
I had to add "babel-runtime" to the dependencies in package.json to get this to run.

Otherwise it would throw:
`Error: Cannot find module 'babel-runtime/core-js/json/stringify'`

I'm using:
* Linux 4.4.0-130-generic
* node v6.14.3
* npm  v3.10.10

**Comment by MikeRalphson** [comment]
I'm really not sure where babel comes into this at all. It's certainly not needed to run the project and there should be no reason for either Node or the front-end to require a polyfill for `JSON.stringify`.

Do you have a full traceback?

**Comment by MikeRalphson** [comment]
Note: think this is a missing dependency in `better-ajv-errors` `package.json`

**Comment by MikeRalphson** [comment]
Fixed in `better-ajv-errors` `v0.5.2`. Updating dependencies now...

**Comment by MikeRalphson** [comment]
Should be fixed in `v1.2.2` - apologies for the wait.
