### ISSUE TITLE
项目很不错

### ISSUE THREAD

**Issue by wstygk** [Mermade/openapi-gui#3]
项目很不错,建议使用element界面组件库加上数据库来开发,
国内有个sosoapi,界面还可以,不过是Java开发的.

**Comment by MikeRalphson** [comment]
Google Translation (x):

**The project is very good**

> The project is very good, it is recommended to use element interface component library plus database to develop, There is a sosoapi, the interface can be, but the development of Java.

**Comment by MikeRalphson** [comment]
谢谢!

Thank you for your kind words.

I think these are both good ideas to move the project forward. I would like to either upgrade Bootstrap to version 4, or replace it with a Vue.js compatible component library.

As for a database backend I need to give this some more thought, maybe so solutions are pluggable.

**Comment by MikeRalphson** [comment]
sosoapi - simple online/simple offline has a demo [here](http://www.sosoapi.com/pass/apidoc/demo.htm) - seems to be a cloud storage API.
