### ISSUE TITLE
Create a new response with some usability issues.  

### ISSUE THREAD

**Issue by renweibo** [Mermade/openapi-gui#31]
This is a great tool and thanks for your work. And I got some usability issue, if anything misunderstand, please correct me. Thanks!

After create a new operation with default value, then create a new response. There are some issues:

- the layout for operation is too wide and without scroll bar to see the full part the html gui. Can you add a scroll bar to scroll from left to right.
- the default response has no schema edit action support. It only show "status code" and "Description". User cannot create a new media type. It's better to provide a default media type.
- the duplicate button for response does not work. It will show error on js console
```
Uncaught ReferenceError: duplicateResponse is not defined
    at click (eval at Tn (vue.min.js:6), <anonymous>:3:14340)
    at e (vue.min.js:6)
    at HTMLAnchorElement.t._withTask.t._withTask (vue.min.js:6)
```
- for existing media type of the response. I don't find any way to change the schema.

All these issues can reproduce on online editor https://mermade.github.io/openapi-gui/#

**Comment by MikeRalphson** [comment]
Thanks for the report, I'll take a look.

**Comment by MikeRalphson** [comment]
Tackling your issues one by one:

> the layout for operation is too wide and without scroll bar to see the full part the html gui. Can you add a scroll bar to scroll from left to right.

What resolution are you running at? For example I'm running at 1366x768. Temporary workaround: you might try changing your browser's zoom setting for `openapi-gui` to something less than 100% (I use 90% out of habit because of this display's low vertical resolution).

**Comment by MikeRalphson** [comment]
> The default response has no schema edit action support. It only show "status code" and "Description". User cannot create a new media type

Ability to create media-type objects has been added.

**Comment by MikeRalphson** [comment]
> for existing media type of the response. I don't find any way to change the schema.

This should be as simple as using the 'edit schema' button. Can you confirm if that's what you mean by "change the schema"?

**Comment by renweibo** [comment]
> > for existing media type of the response. I don't find any way to change the schema.
> 
> This should be as simple as using the 'edit schema' button. Can you confirm if that's what you mean by "change the schema"?

Let me explain this, "change the schema" here is not modify the schema. It's "switch to different schema". I can edit the schema. But sometime, it will be helpful just to replace current schema with another one which already exists.

**Comment by renweibo** [comment]
> Tackling your issues one by one:
> 
> > the layout for operation is too wide and without scroll bar to see the full part the html gui. Can you add a scroll bar to scroll from left to right.
> 
> What resolution are you running at? For example I'm running at 1366x768. Temporary workaround: you might try changing your browser's zoom setting for `openapi-gui` to something less than 100% (I use 90% out of habit because of this display's low vertical resolution).

I use the same work around as you said and other way to get things done. 
MBP 15# is my code station. The default resolution 1440x900.

**Comment by MikeRalphson** [comment]
Thanks for the additional clarifications.
