### ISSUE TITLE
Bearer Authentication

### ISSUE THREAD

**Issue by alexgoldstone** [Mermade/openapi-gui#32]
There does not seem to be a mechanism to define Bearer Authentication using JWT as documented here:

https://swagger.io/docs/specification/authentication/bearer-authentication/

Or am I missing something obvious?

**Comment by MikeRalphson** [comment]
Thanks for pointing this out. The missing field `bearerFormat` has been added. It will appear only if `http` authentication is selected and the `scheme` value is exactly `bearer`.

**Comment by MikeRalphson** [comment]
'Fix' reverted (see #33) will try to re-work.

**Comment by MikeRalphson** [comment]
Reinstated, apologies for the delay.
