### ISSUE TITLE
Main tab show empty content.

### ISSUE THREAD

**Issue by renweibo** [Mermade/openapi-gui#33]
Currently, when I access `https://mermade.github.io/openapi-gui/` with the default definition, the `Main` tab show empty page. While other tab like schemas/header/upload/tags works without problem.

**Comment by MikeRalphson** [comment]
Hmmm. Yes. Export to JSON/YAML also blank, but no errors in console...

**Comment by renweibo** [comment]
I see following error. 
![image](https://user-images.githubusercontent.com/6316209/46570960-610c9e00-c99f-11e8-92ad-8544df636621.png)

Not sure if this is the root cause.

**Comment by MikeRalphson** [comment]
I've reverted the change made for #32 temporarily.

**Comment by renweibo** [comment]
It seems the revert fix the problem. 🍻
