### ISSUE TITLE
Invalid `license` and `externalDocs` keys are created

### ISSUE THREAD

**Issue by bobics** [Mermade/openapi-gui#34]
Issue:
OpenAPI-GUI automatically creates **empty** `info -> license` and `paths -> [/path] -> externalDocs` fields, which are invalid per the OpenAPI 3.0 specs. The `license` object requires a `name` field, and `externalDocs` requires a `url` field.

Steps to reproduce:
Load a .yaml file with no license field nor externalDocs field but with paths. Save file.

Expected behavior:
Don't create these fields if they don't already exist. 😄

**Comment by MikeRalphson** [comment]
Can't reproduce. Unless you're using the old OpenAPI / Swagger 2.0 version?

**Comment by bobics** [comment]
Can't repro on latest master either. I was using master around Oct 3rd. I'm pretty sure I was using OpenAPI 3.0 at the time, but could be wrong. Thanks for looking into this, closing issue.
