### ISSUE TITLE
Please support openapi-generator for code generation

### ISSUE THREAD

**Issue by carddamom** [Mermade/openapi-gui#36]
There is now the [openapi-generator](https://github.com/OpenAPITools/openapi-generator), which appears to have take over swagger-codegen for openapi 3.0, could mermade support it for server and client SDK generation?

**Comment by MikeRalphson** [comment]
Do you know if they have a public API server?

**Comment by MikeRalphson** [comment]
From [here](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/online-openapi-generator.md#online-openapi-generator) the answer seems to be "no". It's not even clear from those instructions whether it's possible to run up the API server via Docker. Maybe @wing328 knows?

**Comment by wing328** [comment]
Please refer to https://github.com/OpenAPITools/openapi-generator#openapi-generator-online-docker-image on how to use the OpenAPI Generator Online Docker Image

**Comment by MikeRalphson** [comment]
Thanks @wing328 - I think that should be linked to from the page I originally referenced? Is it possible for someone from OpenAPITools to run the API server on a service such as Heroku (I would but I already have a dyno set up which runs nearly 24/7)?

**Comment by wing328** [comment]
>  I think that should be linked to from the page I originally referenced? 

I took your feedback and update the page with a link to the Docker doc: https://github.com/OpenAPITools/openapi-generator/pull/1415

>  Is it possible for someone from OpenAPITools to run the API server on a service such as Heroku (I would but I already have a dyno set up which runs nearly 24/7)?

We plan to provide an online generator so that people do not need to set up their own. We've contacted several VPS providers but there's no ETA on when we'll be able to offer that.

**Comment by MikeRalphson** [comment]
Thanks @wing328

**Comment by MikeRalphson** [comment]
Saw this on Twitter: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/online-openapi-generator.md

**Comment by MikeRalphson** [comment]
Should be working now, could you please test?

**Comment by carddamom** [comment]
It works! Thank you to both the mermade and OpenApiTools...

**Comment by wing328** [comment]
@MikeRalphson glad to see the integration. Do you mind mentioning "OpenAPI Generator" in the Wizard tab? e.g.

Create server SDK - 39 languages using [OpenAPI-Generator](http://openapi-generator.tech)
Create client SDK - 59 languages using [OpenAPI-Generator](http://openapi-generator.tech)

**Comment by MikeRalphson** [comment]
Links added, thanks.

**Comment by MikeRalphson** [comment]
@wing328 one thing I noticed is that the download links are coming back as follows:

```json
{"code":"56f9553a-0d0a-4c44-b505-b3b5cd34fdb5","link":"http://localhost:8080/api/gen/download/56f9553a-0d0a-4c44-b505-b3b5cd34fdb5"}
```

**Comment by wing328** [comment]
@MikeRalphson I just performed some tests and couldn't repeat the issue:
```
➜  openapi-generator git:(master) curl -X POST -H "content-type:application/json" -d '{"openAPIUrl":"https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml"}' http://api.openapi-generator.tech/api/gen/clients/ruby
{"code":"9763e067-6faa-4a7e-840b-7b795c6666d2","link":"http://api.openapi-generator.tech/api/gen/download/9763e067-6faa-4a7e-840b-7b795c6666d2"}

➜  openapi-generator git:(master) curl -X POST -H "content-type:application/json" -d '{"openAPIUrl":"https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml"}' http://api-latest-master.openapi-generator.tech/api/gen/clients/ruby
{"code":"faf63928-5fba-4bb6-8a26-41232cdb5bb7","link":"http://api-latest-master.openapi-generator.tech/api/gen/download/faf63928-5fba-4bb6-8a26-41232cdb5bb7"}%
```

Can you share more with me? which generator did you target?

**Comment by wing328** [comment]
I also did a test earlier wtih openapi-gui to generate Android client and was able to download the file.

**Comment by MikeRalphson** [comment]
OpenAPI-gui patched out the localhost reference. I'll retest. But this was against stable not latest master.

**Comment by wing328** [comment]
I see. Let me know if I can be of any help to troubleshoot the issue.

**Comment by MikeRalphson** [comment]
```bash
curl -X POST -d '{"spec":{"swagger":"2.0","info":{"title":"","version":""},"paths":{}}}' -H 'content-type: application/json' http://api.openapi-generator.tech/api/gen/servers/haskell
```

```json
{"code":"e64a59b2-b4cd-4076-a6b4-b11bb3836b18","link":"http://localhost:8080/api/gen/download/e64a59b2-b4cd-4076-a6b4-b11bb3836b18"}
```

**Comment by wing328** [comment]
I could repeat the issue with another server generator:
```
➜  openapi-generator git:(master) curl -X POST -H "content-type:application/json" -d '{"openAPIUrl":"https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml"}' https://api.openapi-generator.tech/api/gen/servers/python-flask
{"code":"00932bd5-9530-4115-851b-d5cc878060fd","link":"http://localhost:8080/api/gen/download/00932bd5-9530-4115-851b-d5cc878060fd"}%
```
Looks like it's impacting server but not client generators. We'll look into it.

**Comment by MikeRalphson** [comment]
Great, thanks.

**Comment by wing328** [comment]
@MikeRalphson we've fixed the issue via https://github.com/OpenAPITools/openapi-generator/pull/1580 and deployed the fix to the server. Please give it another try when you've time.

Have a nice weekend.

**Comment by MikeRalphson** [comment]
Thanks, will do!
