### ISSUE TITLE
Shows no media type for a $ref response

### ISSUE THREAD

**Issue by DavidBiesack** [Mermade/openapi-gui#38]
I have an OpenAPI 2.0 document that defines default media types
```yaml
schemes:
  - https

consumes:
  - application/hal+json
  - application/json

produces:
  - application/hal+json
  - application/json
```
The default `produces` media type is used for the in-line 2xx responses.
However, for operations that use `$ref` for a response,  openapi-gui thinks the response does not have a media type, despite the default `produces`.

```yaml
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/blahblahblah'
        '400':
          $ref: '#/responses/400'
```

and later

```yaml
responses:
  '400':
    description: >-
      Bad Request. 
      The request body or one or more of the query parameters was not well
      formed.  The `_error` field in the response will contain details about the
      request error.
    schema:
      $ref: '#/definitions/errorResponse'
```

See screen shot:
<img width="966" alt="screen shot 2018-11-28 at 1 11 36 pm" src="https://user-images.githubusercontent.com/545944/49172970-65569700-f310-11e8-978a-d3041331fca5.png">

I'm using openapi-gui ` "version": "1.2.2",`

**Comment by DavidBiesack** [comment]
... may be an issue with openapi-converter; I'll download that and look at it. Using api-spec-converter, converting my OpenAPI 2.0 to 3.0 yields
```yaml
  responses:
    '400':
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/errorResponse'
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
      description: >-
        Bad Request.  The request body or one or more of the query parameters
        was not well formed.  The `_error` field in the response will contain
        details about the request error.

```

**Comment by DavidBiesack** [comment]
I think this is just an openapi-gui issue; when I download the YAML from openapi-gui ,  I see components/responses/400 structured as with the `api-spec-converter` output above - i.e. the `content` object has the media types.

**Comment by MikeRalphson** [comment]
Thanks @DavidBiesack is it possible for you to share the entire OpenAPI document in a gist?

**Comment by DavidBiesack** [comment]
[This gist](https://gist.github.com/DavidBiesack/2c69315c677992c6582492fc40725c0c) contains an OpenAPI 2.0 source that exhibits the problem.

**Comment by MikeRalphson** [comment]
Should be fixed now.

**Comment by DavidBiesack** [comment]
Confirmed that the fix works on https://mermade.github.io/openapi-gui/ when I upload the gist. I'll let you close when ready. Thanks for the quick fix!

**Comment by MikeRalphson** [comment]
Cool.
