### ISSUE TITLE
Schemas Page Is Blank

### ISSUE THREAD

**Issue by rarcher** [Mermade/openapi-gui#39]
When opened, the `Schemas` page is entirely blank.  This issue was not present a few days ago, and appears to have been introduced in the last several commits.

**Comment by MikeRalphson** [comment]
Can reproduce. Will investigate. Thanks.

**Comment by MikeRalphson** [comment]
Fixed, thanks for letting me know!

**Comment by rarcher** [comment]
No problem, thank you!
