### ISSUE TITLE
Cannot edit schema 

### ISSUE THREAD

**Issue by jdcrecur** [Mermade/openapi-gui#41]
Version: latest at time of writing.
Browser: Chrome latest at time of writing.
Screen: 24" screen 

Cannot edit a schema unless there are enough schema's already in the list.
Requires a min. of 5 schema before you can edit the contents properly.

![screenshot from 2019-01-12 15-19-27](https://user-images.githubusercontent.com/2738844/51074315-02318180-167e-11e9-863c-7c65513cb0d3.png)
![screenshot from 2019-01-12 15-22-37](https://user-images.githubusercontent.com/2738844/51074317-05c50880-167e-11e9-8486-cc1ce6060055.png)
![screenshot from 2019-01-12 15-23-57](https://user-images.githubusercontent.com/2738844/51074320-1b3a3280-167e-11e9-852d-26ca73d41202.png)

Taking the flexbox and overflow hidden off seems to fix it (there is a js error thought too though, don't know if this is related):
![screenshot from 2019-01-12 15-30-02](https://user-images.githubusercontent.com/2738844/51074399-ff835c00-167e-11e9-8c42-bcc6f5c21aad.png)

**Comment by jdcrecur** [comment]
Actually wait that does not fix it, once the list of attributes gets too long for the modal window it becomes un-usable again :/

**Comment by MikeRalphson** [comment]
Thanks for the report. Will try and reproduce.

**Comment by MikeRalphson** [comment]
Reproduced in Firefox 64.0 and Chrome 70.0 so I think this is a generic layout/CSS bug. Thanks again for the report.

**Comment by jdcrecur** [comment]
Yup this has resolved the bug. Thanks!
