### ISSUE TITLE
Response status codes not working

### ISSUE THREAD

**Issue by gren236** [Mermade/openapi-gui#43]
This problem can be reproduced by adding a new response status code in path operation. When you add a new one after a default 200 code, it increments (201, 202...). Then, I change the incremented value (eg 201 to 401) and add a description. After that, status code changes back to incremented 201, and when i change it back and save, it is still 201 in the resulting json/yaml.

**Comment by MikeRalphson** [comment]
Thanks for the report. Will take a look.

**Comment by MikeRalphson** [comment]
Console message:

> TypeError: this.$parent.renameResponse is not a function method.js:245:17

**Comment by MikeRalphson** [comment]
Should be fixed now, please chase if not. Thanks for the report.
