### ISSUE TITLE
Duplicating a path bug

### ISSUE THREAD

**Issue by mniinio** [Mermade/openapi-gui#44]
Duplicating paths results into duplicating operation urls when editing (same id's with duplicated operations or something?). Steps to produce:

1. I created a path and 1 operation under it and gave both a URL, for example /docs
2. I clicked the duplicate -icon on the path level and it created a /newPath.
3. I changed the /newPath to /emails
4. I then edited the operation to /emails *and that changed the original paths operation to emails, too while I edited*

**Comment by MikeRalphson** [comment]
Thanks for reporting this. Probable missing call to `clone()`.

**Comment by MikeRalphson** [comment]
Reproduced. As I thought, it was a missing `clone()` call. Should be fixed now, many thanks for reporting.
