### ISSUE TITLE
Settings Link is broken

### ISSUE THREAD

**Issue by lexfrei** [Mermade/openapi-gui#46]
**Problem:**
Nothing happens on button click

**How to reproduce:**
1. `docker run -dit -p8080:3000 mermade/openapi-gui`
2. Open localhost:8080
3. Click on _Settings_

**Error in log:**
```
VM725:3 Uncaught ReferenceError: settings is not defined
    at click (eval at Tn (vue.min.js:6), <anonymous>:3:430)
    at e (vue.min.js:6)
    at HTMLAnchorElement.t._withTask.t._withTask (vue.min.js:6)
click @ VM725:3
e @ vue.min.js:6
t._withTask.t._withTask @ vue.min.js:6
```

**Tested on:**
Google Chrome Version 73.0.3683.86 (Official Build) (64-bit) with no extensions on Linux and Windows

**Comment by lexfrei** [comment]
Same on manual container build from 6257285a432b6c61461e00200c14728336053f76

**Comment by MikeRalphson** [comment]
The settings link is just a placeholder for functionality in another branch. You're not missing anything that's released yet.

**Comment by lexfrei** [comment]
It's totally confusing for me. The project looks totally working on a quick look. Probably, it's my blindness.
Feel free to close or change this issue.

**Comment by MikeRalphson** [comment]
I agree, it is confusing. I'll disable the settings link and add a tooltip.

**Comment by MikeRalphson** [comment]
Working on this, and will update the live github pages version, but I have a few more dependencies which need updating before I rebuild the docker container.

**Comment by MikeRalphson** [comment]
Docker image rebuilt and published.
