### ISSUE TITLE
Can't create a HTTP Authentication security scheme

### ISSUE THREAD

**Issue by alastair-todd** [Mermade/openapi-gui#47]
I see #32 talks about the same thing but for me it seems glitched.

All the other options change the form fields, but the http one does nothing. If I save one with http, you cannot edit it.

I guess I can just add this manually its fine. 

```
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT  
```

**Comment by MikeRalphson** [comment]
Thanks for the report. Do you see any errors in the javascript console?

**Comment by alastair-todd** [comment]
When I select the HTTP Authentication type option - its not much to go on !

> vue.min.js:6 TypeError: Cannot read property 'toLowerCase' of undefined
>     at a.render (eval at Tn (vue.min.js:6), <anonymous>:3:28483)
>     at a.t._render (vue.min.js:6)
>     at a.r (vue.min.js:6)
>     at Kr.get (vue.min.js:6)
>     at Kr.run (vue.min.js:6)
>     at ht (vue.min.js:6)
>     at Array.<anonymous> (vue.min.js:6)
>     at MessagePort.J (vue.min.js:6)
> K @ vue.min.js:6
> z @ vue.min.js:6
> V @ vue.min.js:6
> t._render @ vue.min.js:6
> r @ vue.min.js:6
> Kr.get @ vue.min.js:6
> Kr.run @ vue.min.js:6
> ht @ vue.min.js:6
> (anonymous) @ vue.min.js:6
> J @ vue.min.js:6

(Awesome tool btw)

**Comment by alastair-todd** [comment]
btw its in chrome - ill try FF

**Comment by alastair-todd** [comment]
Looks fine on the petstore but I am no longer able to clear it and upload my own api. remove all no longer does anything. when u click load definition also nothing. breaking change 🥺
