### ISSUE TITLE
Migrate js/*.js to dependencies

### ISSUE THREAD

**Issue by DanielRuf** [Mermade/openapi-gui#54]
We should not host the thirdparty / vendor code in there but use npm to put them there or create a bundle (using webpack or rollup).

**Comment by MikeRalphson** [comment]
Thanks, but no thanks. One advantage of the current approach is we can instantly deploy to github pages or use any of the other deployment / running methods without a build step, and that's definitely an advantage I'd like to keep.

**Comment by DanielRuf** [comment]
Well, did you already try Netlify or Zeit Now?

**Comment by MikeRalphson** [comment]
No, why would I? The project is hosted on github already, the path of least resistance is github pages.
