### ISSUE TITLE
The button "Remove all" not work

### ISSUE THREAD

**Issue by tailot** [Mermade/openapi-gui#58]
Hi, the button "Remove all" not work.
Every time I have to clean the file manually.

![image](https://user-images.githubusercontent.com/40148896/68628790-f3a43880-04e1-11ea-8670-a37e4c530b49.png)

Regards

**Comment by MikeRalphson** [comment]
Hmm, can't reproduce this. Are you pressing `Load` after `Remove All` (which will effectively immediately undo the remove-all operation)?

**Comment by tailot** [comment]
@MikeRalphson No I’m just clicking on "remove all", it seems to work only for the "main" section. The schemas are intact, is the expected behavior ?

**Comment by MikeRalphson** [comment]
I've separated this function out into two buttons now, `Remove Paths` and `Remove All`. Thanks for reporting.
