### ISSUE TITLE
ReactJS integration support ?

### ISSUE THREAD

**Issue by vantony-dev** [Mermade/openapi-gui#60]
Do we have the support to import and integrate it in ReactJS component. I have currently tried with npm module of OpenAPI GUI and it is not working.

**Comment by MikeRalphson** [comment]
Hi, the npm module is designed to provide a more intelligent backend application for openapi-gui, not for allowing the building / bundling of the app as a web component.

As the project is written in Vue.js (and I have no real experience in React) I guess it would at least cause some bloat / duplication if the app was wrapped inside an React component.  It also uses custom code to provide a zero-build environment unlike that which is normal for React or Vue projects which are scaffolded by the usual CLI tools.

Also, as the app is designed to work full-screen and not be embedded, I wonder how well that would really work, but would be interested to hear more about your use-case.

**Comment by vantony-dev** [comment]
I believe embedding the Vue application into React will run into issues, So now I'm manually porting the whole application to ReactJS by keeping the main functionalities.

**Comment by MikeRalphson** [comment]
Ok, don't hesitate to ask if you hit any problems.
