### ISSUE TITLE
The syntax-highlighting for the "Export YAML" output doesn't escape ' properly

### ISSUE THREAD

**Issue by niklasskoldmark** [Mermade/openapi-gui#64]
### Minimal reproducible test case:
If you change the "title" of the test-project from "Swagger Petstore" to "Swagger's Petstore"
The beginning of the "Export YAML" output is:
```yaml
openapi: 3.0.0
servers:
  - url: 'http://petstore.swagger.io/v2'
info:
  description: >-
    :dog: :cat: :rabbit: This is a sample server Petstore server.  You can find
    out more about Swagger at [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you
    can use the api key `special-key` to test the authorization filters.
  version: 1.0.0
  title: Swagger's Petstore
  termsOfService: 'http://swagger.io/terms/'
```
It is valid YAML, but the syntax-highlighting shows 
```
's Petstore
termsOfService: '
```
in red as if it's a continuous quoted string

**Comment by MikeRalphson** [comment]
Thanks, will check if updating highlight.js fixes this.

**Comment by MikeRalphson** [comment]
Upgraded to a custom build of highlight.js with just the languages required. Thanks for reporting this.
