### ISSUE TITLE
always display petstore

### ISSUE THREAD

**Issue by sify21** [Mermade/openapi-gui#65]
I started the docker image with
```
docker run --name openapi-gui -v /root/containers/openapi/data:/data -p 8080:3000 -d mermade/openapi-gui npm start -- -d /data/oai.yaml -l -w
```
in container, I can see processes
```
PID   USER     TIME  COMMAND
    1 root      0:00 npm
   23 root      0:01 node openapi-gui.js -d /data/oai.yaml -l -w
```
However, when I go to browser and clear cache and visit main page, it still displays petstore.
And if I hit the save button, the content of /data/oai.yaml will change to petstore.
It seems that `-w` option is working

**Comment by sify21** [comment]
Is this a problem only related to the dockerized app? It will display the correct content when run on bare metal? I dont have node env so I cant verify.

**Comment by MikeRalphson** [comment]
Yes, I've just tested it locally and it works serving the given OpenAPI document.

**Comment by sify21** [comment]
Maybe it's a platform issue? I tested branch master on centos8 bare metal, it's the same behavior.
I start the app with
```
npm start -- -d ../data/oai.yaml -l -w -p 8080

> openapi-gui@1.2.2 start /root/containers/openapi/openapi-gui
> node openapi-gui.js "-d" "../data/oai.yaml" "-l" "-w" "-p" "8080"

OpenAPI GUI server listening at http://:::8080
Serving ../data/oai.yaml
Launching...
Could not open http://localhost:8080/?url=%2fserve
```
Then I go to browser, clear the cache and reload the page, it displays petstore.

Does this warnning matter? It appears when I run `npm install`
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by sify21** [comment]
I found the problem. I need to add this parameter `?url=%2fserve` to display the content of my document

**Comment by MikeRalphson** [comment]
Thanks - will add an example in the README as you suggest.

**Comment by MikeRalphson** [comment]
`README.md` updated.
