### ISSUE TITLE
[v3] Page will not load after importing invalid spec

### ISSUE THREAD

**Issue by tulir** [Mermade/openapi-gui#7]
I removed the `info` section in the import box and imported the spec. The import was successful (according to the popup modal), but when I reloaded the page it just turned blank and the console contained [errors](https://pastebin.com/ZBGTQx49). Also, the console had `TypeError: openapi.info is undefined` right after importing.

Steps to reproduce:
1. Remove the whole `info` and/or `servers` section from the JSON box in the `Upload` tab
2. Click `Load Definition`
3. Refresh the page

The problem seems to be that the uploaded definitions aren't properly validated and/or fixed.

**Comment by MikeRalphson** [comment]
@tulir Thanks for the bug report! Have added to the pre-processing of the definition a check that the info object and mandatory properties are defined. Seems to fix the problem for me, but if you get a chance to retest?

**Comment by tulir** [comment]
Removing the `info` object works fine now, but removing the `servers` array will still break the page.

**Comment by MikeRalphson** [comment]
Detection of missing servers array now fixed.

**Comment by tulir** [comment]
Seems to work now, thanks!
