### ISSUE TITLE
Add a rendered preview of the api

### ISSUE THREAD

**Issue by CubicrootXYZ** [Mermade/openapi-gui#77]
**What**
Use a opanapi rendering tool like redoc or the swagger ui to generate a preview of the api documentation. 

Ideally this is created on-change of any documentation and displayed split-screen like.

**Why**

Immeadiately see the changes you make. This will make it much more convenient especially for users not that familiar with the openapi spec.

**Comment by MikeRalphson** [comment]
This project takes a different approach, that of a form-builder rather than a text editor with a rendered view like swagger-editor or projects which preview with ReDoc.

It is not intended to work like or compete with those projects.
